filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Code Folding
set foldmethod=indent
set foldlevel=99
set number

" Indenting
set nocompatible
set ruler
set nosmartindent
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set showmatch
set linebreak
" Hit indentation levels instead of -4/+4
set shiftround 

" Hide buffers don't delete
set hidden

" Window Split Movement
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" TaskList
map <leader>td <Plug>TaskList

" Revision History
map <leader>g :GundoToggle<CR>

" Syntax Highlighting
syntax on

" Try to detect filetypes
filetype on

" enable loading indent file for filetype
filetype plugin indent on 

" Python Auto Completion
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

" RopeVim (Refactoring Tools)
map <leader>j :RopeGotoDefinition<CR>
map <leader>r :RopeRename<CR>

" Searching
nmap <leader>a <Esc>:Ack!

" Status Line Settings
set showmode
set showcmd
set mouse=a
set ruler
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P
set statusline+=%{fugitive#statusline()}

map <Leader>] <Plug>MakeGreen " change from <Leader>t to <Leader>]

" NERDTree Mapping
map <Leader>n :NERDTreeToggle<CR>

" Highligh all search pattern matches
set hlsearch

" Add the virtualenv's site-packages to vim path
py << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF

" Javascript Specific
autocmd FileType javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Sass specific
autocmd FileType sass setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Jinja2 file extension
autocmd BufNewFile,BufRead *.jinja set filetype=jinja

" System Clipboard support
set clipboard=unnamed

" Disable audio beeping
set vb

" Run linter on the fly
let g:pymode_lint_onfly = 1

" Don't open quickfix for pylint
let g:pymode_lint_cwindow = 0

" File Tab complete 
set wildmenu
