set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'wincent/Command-T'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-surround'
Plugin 'ervandew/supertab'
Plugin 'fholgado/minibufexpl.vim'
Plugin 'mileszs/ack.vim'
Plugin 'sjl/gundo.vim'
Plugin 'alfredodeza/pytest.vim'
Plugin 'reinh/vim-makegreen'
Plugin 'vim-scripts/TaskList.vim'
Plugin 'vim-scripts/The-NERD-tree.git'
Plugin 'tpope/vim-haml'
Plugin 'lambdalisue/nose.vim'
Plugin 'Glench/Vim-Jinja2-Syntax'
Plugin 'rodjek/vim-puppet'
Plugin 'wojtekmach/vim-rename'
Plugin 'klen/python-mode'
Plugin 'pangloss/vim-javascript'
Plugin 'briancollins/vim-jst'
Plugin 'scrooloose/syntastic'
Plugin 'fatih/vim-go'
Plugin 'kchmck/vim-coffee-script'
Plugin 'saltstack/salt-vim'
Plugin 'stephpy/vim-yaml'
Plugin 'wookiehangover/jshint.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'markcornick/vim-terraform'

call vundle#end()

" Code Folding
set foldmethod=indent
set foldlevel=99
set number

" Indenting
set ruler
set nosmartindent
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set showmatch
set linebreak
" Hit indentation levels instead of -4/+4
set shiftround 

" Hide buffers don't delete
set hidden

" Window Split Movement
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" TaskList
map <leader>td <Plug>TaskList

" Revision History
map <leader>g :GundoToggle<CR>

" Syntax Highlighting
syntax on

" Try to detect filetypes
filetype on

" enable loading indent file for filetype
filetype plugin indent on 

" Python Auto Completion
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "<C-Tab>"
set completeopt=menuone,longest,preview

" RopeVim (Refactoring Tools)
map <leader>j :RopeGotoDefinition<CR>
map <leader>r :RopeRename<CR>

" Searching
nmap <leader>a <Esc>:Ack!

" Status Line Settings
set showmode
set showcmd
set mouse=a
set ruler
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P
set statusline+=%{fugitive#statusline()}

map <Leader>] <Plug>MakeGreen " change from <Leader>t to <Leader>]

" NERDTree Mapping
map <Leader>n :NERDTreeToggle<CR>

" Highligh all search pattern matches
set hlsearch

" Add the virtualenv's site-packages to vim path
py << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF

" Javascript Specific
autocmd FileType javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2

" YAML Specific
autocmd FileType yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Sass specific
autocmd FileType sass setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Scss specific
autocmd FileType scss setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Ruby specific
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2

" EJS File extension
autocmd BufNewFile,BufRead *.ejs set filetype=html

" Jinja2 file extension
autocmd BufNewFile,BufRead *.jinja set filetype=jinja

" VEfile file
autocmd BufNewFile,BufRead VEfile set filetype=yaml

" Markdown files
autocmd BufNewFile,BufRead *.md set filetype=markdown

" System Clipboard support
set clipboard=unnamed

" Disable audio beeping
set vb

" Run linter on the fly
let g:pymode_lint_onfly = 1

" Don't open quickfix for pylint
let g:pymode_lint_cwindow = 0

" Ignore these pylint warning
let g:pymode_lint_ignore = "W404"

let g:pymode_repo_guess_project = 0

let g:pymode_rope_completion = 0

" File Tab complete 
set wildmenu

" Ignore warnings in javascript
let g:syntastic_quiet_messages = {'level': 'warnings'}

let g:syntastic_ignore_files=['\c.*\.rst']

let g:ycm_key_list_select_completion = ['<C-TAB>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-S-TAB>', '<Up>']
